### ISSUE TITLE
Create correct keys

### ISSUE THREAD

**Issue by pikesley** [mastodon-me-uk/instance-configuration#26]
We need, as a Github Repository Secret (or possibly an Org Secret?), a key called [`MASTODON_READ_ONLY_KEY` with the `admin:read` scope](https://github.com/mastodon-me-uk/instance-configuration/blob/main/playbook/roles/measures/README.md)

Once this is in play, the [Configure Mastodon Instance](https://github.com/mastodon-me-uk/instance-configuration/actions/workflows/run-ansible.yaml) should work and we should be able to see the `measures` data, which should resolve #3

**Comment by Floppy** [comment]
I completely forgot to do this, sorry. Will do today.

**Comment by Floppy** [comment]
Added the key, now back to "This action is not allowed" error, so I'm obviously still doing something wrong.

**Comment by pikesley** [comment]
Can you make a temporary key with `admin:read` and let me test with it pls?

**Comment by Floppy** [comment]
sent!

**Comment by Floppy** [comment]
Working!
