### ISSUE TITLE
Create GitHub action to deploy configuration to instance automatically

### ISSUE THREAD

**Issue by Floppy** [mastodon-me-uk/instance-configuration#3]
Create a github action to deploy configuration via the Mastodon REST API: https://docs.joinmastodon.org/methods/admin/

Could be done via ansible, terraform, or something completely custom?

**Comment by Floppy** [comment]
https://github.com/hachyderm/hack is something I've seen that uses the API to set this sort of thing. We could use that, adapt, or do something else.

**Comment by Floppy** [comment]
I feel like ansible REST configs could do the job nicely. https://opensource.com/article/21/9/ansible-rest-apis

**Comment by pikesley** [comment]
Does this config exist somewhere already? Or do we need to extract from the instance first?

**Comment by Floppy** [comment]
There is stuff in this repo, but not in the right form yet probably. Starting with a dummy NOOP seems like a good start, then we can roll it out across different aspects of the config.

**Comment by Floppy** [comment]
Maybe that no-op could get https://docs.joinmastodon.org/methods/admin/measures/#get - it would prove that admin access is working.

**Comment by pikesley** [comment]
OK I finally got Mastodon working locally and I can indeed hit up the API successfully

**Comment by Floppy** [comment]
Nice!

**Comment by pikesley** [comment]
I have some [very Noddy Ansible](https://github.com/pikesley/mastible) but it [works](https://github.com/pikesley/mastible/actions/runs/3555336048/jobs/5971973787#step:3:14)

**Comment by Floppy** [comment]
Even nicer!!

**Comment by pikesley** [comment]
How would you like to integrate this stuff?

**Comment by pikesley** [comment]
I have Thoughts: this is going to require some Python or something beyond what Ansible gives us. For example, applying the blocklist will require iterating through the CSV and [POSTing here for each line](https://docs.joinmastodon.org/methods/admin/domain_blocks/#create) (I think, unless I've misunderstood something)

(I am of course keen to do this)

**Comment by Floppy** [comment]
I think my ideal is that it runs as a github action on this repo that sets the remote content to whatever is here, in the canonical source. There's nothing fixed here about the format we store things in, so we can change anything we like. For instance, the blocklist could be a set of separate files, or actually in ansible-compatible YAML that it can iterate through natively.

I think if we start with an action that does the login check as you have it there, with the appropriate env vars set up, so it connects to the real thing, then perhaps auto-updating the about page next, as that should be reasonably simple?

**Comment by Floppy** [comment]
What API key does it need in MASTODON_TOKEN? How did you generate that for your test site?

**Comment by pikesley** [comment]
I'll send you a screenshot or something later. Also if you add me to this org I can add my code in here

**Comment by Floppy** [comment]
done 👍🏻

**Comment by pikesley** [comment]
For the API key, I created an application (as `admin`) and gave it the `admin:read` and `admin:write` scopes (although for this first iteration, `admin:read` should be sufficient). It gives you a `client key` and `client secret` on the assumption that you're remotely interested in battling with `Oauth`, but it turns out *you can completely ignore Oauth* because all you need is the `access token`, which should go into `MASTODON_TOKEN`.

Down the road we should probably assign different keys with different scopes for different tasks, but for now, this will work.

**Comment by pikesley** [comment]
There is a [PR](https://github.com/mastodon-me-uk/instance-configuration/pull/12)

**Comment by Floppy** [comment]
Well, it sort of worked, until I pointed it at the real thing, then it didn't. Getting a 403, I wonder if my token permissions are wrong...

**Comment by pikesley** [comment]
Did you copy-paste the token? Because when I did that and dropped it into Postman, it came with leading and trailing spaces which broke it

**Comment by Floppy** [comment]
I may have indeed. I'll check.

**Comment by Floppy** [comment]
My god, there's actually a useful error message in the response. Looks like my scopes are wrong: `{"error": "This action is outside the authorized scopes"}`

**Comment by pikesley** [comment]
I cannot see an API endpoint for updating the `about` page

**Comment by Floppy** [comment]
I think you're right! That might have to be a manual job for now, then.

**Comment by pikesley** [comment]
Think we can close this now
